import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Naus Ai",
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}   light:bg-[#fcfcfc] duration-700 dark:bg-[#000] dark:duration-700 selection:bg-[#FF7795] selection:text-white dark:selection:text-white`} >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
